### ISSUE TITLE
[bug] magento 2.4.2

### ISSUE THREAD

**Issue by nordcomputer** [aune-io/magento2-autoinvoice#16] opened 2021-02-16 09:34 UTC
The extensions seems to throw an error when updating to magento 2.4. I wasnt able to track down the responsible file yet. Any suggestions?

```
bin/magento setup:upgrade -vvv                                                                                                                 
Cache types config flushed successfully
Cache cleared successfully
File system cleanup:
/app/generated/code/Aune
/app/generated/code/Composer
/app/generated/code/Magento
/app/generated/code/Psr
/app/generated/code/Symfony
The directory '/app/generated/metadata/' doesn't exist - skipping cleanup
Updating modules:
Area code is not set

In State.php line 153:
                                                    
  [Magento\Framework\Exception\LocalizedException]  
  Area code is not set                              
                                                    

Exception trace:
  at /app/vendor/magento/framework/App/State.php:153
 Magento\Framework\App\State->getAreaCode() at /app/generated/code/Magento/Framework/App/State/Interceptor.php:50
 Magento\Framework\App\State\Interceptor->getAreaCode() at /app/vendor/magento/module-theme/Model/Theme.php:272
 Magento\Theme\Model\Theme->getArea() at /app/vendor/magento/framework/View/File/Collector/Base.php:68
 Magento\Framework\View\File\Collector\Base->getFiles() at /app/vendor/magento/framework/View/File/Collector/Decorator/ModuleOutput.php:59
 Magento\Framework\View\File\Collector\Decorator\ModuleOutput->getFiles() at /app/vendor/magento/framework/View/File/Collector/Decorator/ModuleDependency.php:63
 Magento\Framework\View\File\Collector\Decorator\ModuleDependency->getFiles() at /app/vendor/magento/framework/View/Layout/File/Collector/Aggregated.php:88
 Magento\Framework\View\Layout\File\Collector\Aggregated->getFiles() at /app/vendor/magento/framework/View/Element/UiComponent/Config/FileCollector/AggregatedFileCollector.php:76
 Magento\Framework\View\Element\UiComponent\Config\FileCollector\AggregatedFileCollector->collectFiles() at /app/vendor/magento/module-ui/Config/Reader/FileResolver.php:43
 Magento\Ui\Config\Reader\FileResolver->get() at /app/vendor/magento/module-ui/Config/Reader/Definition.php:28
 Magento\Ui\Config\Reader\Definition->read() at /app/vendor/magento/module-ui/Config/Reader/Definition/Data.php:89
 Magento\Ui\Config\Reader\Definition\Data->initData() at /app/vendor/magento/module-ui/Config/Reader/Definition/Data.php:75
 Magento\Ui\Config\Reader\Definition\Data->__construct() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:206
 Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:182
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /app/vendor/magento/framework/View/LayoutFactory.php:50
 Magento\Framework\View\LayoutFactory->create() at /app/vendor/magento/module-payment/Helper/Data.php:79
 Magento\Payment\Helper\Data->__construct() at /app/generated/code/Magento/Payment/Helper/Data/Interceptor.php:14
 Magento\Payment\Helper\Data\Interceptor->__construct() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121
 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:170
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:70
 Magento\Framework\ObjectManager\ObjectManager->get() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:206
 Magento\Framework\ObjectManager\Factory\AbstractFactory->parseArray() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:182
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:276
 Magento\Framework\ObjectManager\Factory\AbstractFactory->getResolvedArgument() at /app/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:239
 Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgumentsInRuntime() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:34
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->_resolveArguments() at /app/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:59
 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() at /app/vendor/magento/framework/ObjectManager/ObjectManager.php:56
 Magento\Framework\ObjectManager\ObjectManager->create() at /app/vendor/magento/framework/Console/Cli.php:153
 Magento\Framework\Console\Cli->getApplicationCommands() at /app/vendor/magento/framework/Console/Cli.php:134
 Magento\Framework\Console\Cli->getDefaultCommands() at /app/vendor/symfony/console/Application.php:1274
 Symfony\Component\Console\Application->init() at /app/vendor/symfony/console/Application.php:629
 Symfony\Component\Console\Application->find() at /app/vendor/symfony/console/Application.php:237
 Symfony\Component\Console\Application->doRun() at /app/vendor/magento/framework/Console/Cli.php:115
 Magento\Framework\Console\Cli->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/bin/magento:23
```

When I disable the module, the upgrade works as expected.

**Comment by renatocason** [comment] 2021-02-16 18:27
Hi @nordcomputer ,

I don't have an M2.4.2 environment at hand, but I think it's a problem with the dependency chain on `InvoiceProcess`. I made a change to include it via factory on the cron and the command on branch `hotfix/2.1.2`, would you be able to test that out and let me know if that works?

Thanks,
Renato

**Comment by nordcomputer** [comment] 2021-02-16 18:35
I will do tomorrow. Thank you.

**Comment by nordcomputer** [comment] 2021-02-22 19:59
Is it maybe, that the files for Unit-Tests also have to be changed?
There is also an `InvoiceProcessInterface` left in `Model/InvoiceProcess.php`

**Comment by renatocason** [comment] 2021-02-22 22:22
Hi @nordcomputer ,

I tried to set up an instance of Magento 2.4.2 with PHP 7.3 and couldn't reproduce the issue, neither on `setup:upgrade` nor on `setup:di:compile`.
The fact that `InvoiceProcessInterface` is used in the class that implements it is absolutely normal and the Unit Tests shouldn't be included in those stages. The only thing I can suggest is for you to try and remove what you think might be causing the issue.
As I can't reproduce the issue on a vanilla setup of the same version, there is not really much more I can do to help you - sorry about that.

Regards,
Renato

**Comment by nordcomputer** [comment] 2021-02-22 23:27
No problem - I will try to redo my setup.

**Comment by nordcomputer** [comment] 2021-02-23 08:51
Seems to work now - I guess it was a caching problem. After compiling, clearing the static cache and the normal cache, I dont get any errors. A new release would be nice ;-)

**Comment by renatocason** [comment] 2021-02-23 08:58
Hi @nordcomputer ,

Great news, thanks - release 2.1.2 created.
I will close this issue for now but feel free to reopen it in case there is something wrong with that.

Thanks,
Renato

**Closed by renatocason** 2021-02-23 08:58 UTC
